### ISSUE TITLE
Angular, HomeWork 1, Task 1-2

### ISSUE THREAD

**Issue by DinamickaDevelopment** [inferal/yura_pogorelov#1]
Примеры не закончены, требуют доработки.

**Comment by inferal** [comment]
Все вроде да работал.
И в чем именно заключается доработка

**Comment by DinamickaDevelopment** [comment]
Другое дело, что то не то было в предыдущем варианте. 
Кодировку нужно бы еще поправить во втором примере, русские буквы не отображаются.

**Comment by inferal** [comment]
Добавил поддержку `<meta charset="UTF-8">` в Task2.
Хотя у меня вроде все нормально отображается.
А первом случае был косяк с загрузкой на git
